### ISSUE TITLE
Can this used with EF Core 3.x?

### ISSUE THREAD

**Issue by jovball** [holajan/OracleCore3EF64Sample#1]
Oracle is dragging their feet on EF Core 3.x support. Will this work for that?

**Comment by holajan** [comment]
No, sorry. This is only for Entity Framework 6.4 in .NET Core 3.x.

**Comment by ajay-verma-01** [comment]
Hi Jan,
Could you please give access to new Oracle.ManagedDataAccess.EntityFramework which is built for .Net Core?

Thank you,
